#!/bin/sh

# Exit on error
set -e

export DEB_BUILD_MAINT_OPTIONS="hardening=+all,-fortify"
export DEB_CPPFLAGS_MAINT_APPEND="-D_FORTIFY_SOURCE=3"

# Run the unit tests.
dh_autoreconf
dh_auto_configure
dh_auto_build
dh_auto_test