#!/bin/bash

set -e

USER="bitcoin"

case "$1" in
  purge)
    if getent passwd $USER >/dev/null; then
      userdel --remove $USER || true
    fi
    
    if [ -d "/etc/bitcoin" ]; then
      rm -rf /etc/bitcoin || true
    fi
    
    if [ -d "/var/lib/bitcoin" ]; then
      rm -rf /var/lib/bitcoin || true
    fi
    
    if [ -d "/run/bitcoind" ]; then
      rm -rf /run/bitcoind || true
    fi
    ;;
    
  upgrade|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

#DEBHELPER#

exit 0
