#!/bin/bash

set -e

USER="bitcoin"

case "$1" in
  purge)
    if getent passwd $USER >/dev/null; then
      deluser --system $USER || true
    fi
    
    dpkg-statoverride --remove --force-statoverride-remove /etc/bitcoin/bitcoin.conf
    dpkg-statoverride --remove --force-statoverride-remove /var/lib/bitcoin
    ;;
    
  upgrade|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

#DEBHELPER#

exit 0
