#!/bin/bash

set -e

USER="bitcoin"

case "$1" in
  configure|reconfigure)

  if ! getent passwd $USER >/dev/null; then
      useradd --system --user-group $USER >/dev/null || true
  fi
  
  if [ -d "/etc" ]; then
    if [ ! -d "/etc/bitcoin" ]; then
      mkdir -p /etc/bitcoin
      chown $USER:$USER /etc/bitcoin
    fi
    if [ ! -f "/etc/bitcoin/bitcoin.conf" ]; then
      runuser -u $USER touch /etc/bitcoin/bitcoin.conf
      runuser -u $USER -- bash -c "echo -e 'txindex=1 \nserver=1' > /etc/bitcoin/bitcoin.conf"
    fi
  fi
  
  if [ -d "/var/lib" ]; then
    if [ ! -d "/var/lib/bitcoin" ]; then
      mkdir -p /var/lib/bitcoin
      chown $USER:$USER /var/lib/bitcoin
    fi
  fi
  
  if [ -d "/run" ]; then
    if [ ! -d "/run/bitcoind" ]; then
      mkdir -p /run/bitcoind
      chown $USER:$USER /run/bitcoind
    fi
  fi
  ;;
esac

#DEBHELPER#

exit 0
